name: luacheck
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          luacheckrc_url: https://raw.githubusercontent.com/MrAsyncRblx/RbxBoilerplate/master/.luacheckrc?token=ABK3UGFXFYEFHQJWMDBW77DAJUYIC
